apiVersion: apps/v1
kind: Deployment
metadata:
  name: frozenyogurtshop-username
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frozenyogurtshop-username
  template:
    metadata:
      name: frozenyogurtshop-username
      labels:
        app: frozenyogurtshop-username
    spec:
      containers:
      - name: ovs
        image: jaibw/frozenyogurtshop:latest 
        ports:
        - containerPort: 80 

---
apiVersion: v1
kind: Service
metadata:
  name: frozenyogurtshop-username
spec:
  type: NodePort
  ports:
  - targetPort: 80 
    port: 80
  selector:
    app: frozenyogurtshop-username
