apiVersion: apps/v1
kind: Deployment
metadata:
  name: frozenyogurtshop-username
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frozenyogurtshop-username
  template:
    metadata:
      name: frozenyogurtshop-username
      labels:
        app: frozenyogurtshop-username
    spec:
      containers:
      - name: web
        image: 677729060277.dkr.ecr.us-west-1.amazonaws.com/website
        ports:
        - containerPort: 80 

---
apiVersion: v1
kind: Service
metadata:
  name: frozenyogurtshop-username
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80 
    port: 80
  selector:
    app: frozenyogurtshop-username
